---
all:
  vars:
    ansible_user: root
    ansible_ssh_extra_args: "-4"
  children:
    hub:
      hosts:
        uptime-pi:
          ansible_host: "{{ host_addresses['uptime-pi'] }}"
          ansible_user: pi
          beszel_app_url: "https://uptime-pi.zebra-alewife.ts.net:8443"
    agents:
      hosts:
        koorax:
          ansible_host: "{{ host_addresses['koorax'] }}"
        kraemer:
          ansible_host: "{{ host_addresses['kraemer'] }}"
        server01:
          ansible_host: "{{ host_addresses['server01'] }}"
        unstable:
          ansible_host: "{{ host_addresses['unstable'] }}"
        forum:
          ansible_host: "{{ host_addresses['forum'] }}"
        spof:
          ansible_host: "{{ host_addresses['spof'] }}"
        unseven:
          ansible_host: "{{ host_addresses['unseven'] }}"
